[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
license = ""
repository = ""
default-run = "app"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
serde_json = "1"
serde = { version = "1", features = [ "derive" ] }
tauri = { version = "1", features = ["api-all", "cli"] }
mime_guess = "2"
dirs = "4"
url = "2"
base64 = "0"
chrono = "0"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
