name: CI

env:
  CI: true

on:
  push:
    branches:
      - "**"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm run lint
    - run: npx playwright install --with-deps chromium
    - run: npm test

  tauri:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo
          ./src-tauri/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - run: npm run tauri build
    - name: install stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo test
      working-directory: ./src-tauri
