name: CI

env:
  CI: true

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: npm install
    - run: npx playwright install --with-deps chromium
    - run: npm run lint
    - run: npm test
    - run: npm run dist
    - run: cargo test
      working-directory: ./src-tauri
