name: Release

env:
  CI: true

on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: 1.0.0
        required: true

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: dmg
          path: src-tauri/target/release/bundle/dmg/*
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3
      - run: npm install
      - run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: deb
          path: src-tauri/target/release/bundle/deb/*
  release:
    needs: [mac, ubuntu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dmg
      - uses: actions/download-artifact@v3
        with:
          name: deb
      - name: Display structure of downloaded files
        run: ls -R
      # - uses: ncipollo/release-action@v1
      #   with:
      #     draft: true
      #     artifacts: "src-tauri/target/release/bundle/dmg/TinyWrite_${{github.ref_name}}_x64.dmg,src-tauri/target/release/bundle/deb/tiny-write_${{github.ref_name}}_amd64.deb"
      #     token: ${{ secrets.GITHUB_TOKEN }}
