name: Release

env:
  CI: true

on:
  push:
    tags:
      - '*'

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: TinyWrite.dmg
          path: dist/app
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: TinyWrite.snap
          path: dist/app/TinyWrite.snap
  release:
    needs: [mac, ubuntu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: TinyWrite.dmg
          path: dist/app/
      - uses: actions/download-artifact@v2
        with:
          name: TinyWrite.snap
          path: dist/app/
      - uses: ncipollo/release-action@v1
        with:
          draft: true
          artifacts: "dist/app/TinyWrite.dmg,dist/app/TinyWrite.snap"
          token: ${{ secrets.GITHUB_TOKEN }}
